Review
UnknownHik/TODOlist pull request #1
Opened 2024-10-04 20:37 UTC by UnknownHik

2024-10-05 12:10 UTC, dirtymew requested changes
Привет Алексей

Спасибо что передала PR - теперь оформлено как нужно

Работа очень хорошая :
 - тесты проходят - это самое важное
 - хорошая структура проекта и архитектура
 - понятный код

Дал рекомендации что поправить и улучшить - их немного, думаю стоит поправить  важные мелочи и будем считать что готово

также стоит дописать документацию - описать как запустить настроить и протестировать приложение

2024-10-05 12:10 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.23
лучше одну версию go использовать в go mod go 1.23.1

2024-10-05 12:10 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o /todolist ./cmd/app/main.go
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 это лучше в ENV

2024-10-05 12:10 UTC, dirtymew commented on cmd/app/main.go
> +	"github.com/joho/godotenv"
проблема с импортами по всему проекту - стоит поправить

принято разделять их на 2-3 группы - используй go imports и/или настрой IDE

2024-10-05 12:10 UTC, dirtymew commented on internal/database/database.go
> +        date TEXT NOT NULL,
поле date и  title тоже стоит ограничить

хотя в sqlite это нормально не работает

2024-10-05 12:10 UTC, dirtymew commented on internal/database/database.go
> +	rows, err := db.Query(query, sql.Named("search", search), sql.Named("limit", 20))
лимит стоит в константу вынести

2024-10-05 12:10 UTC, dirtymew commented on internal/database/database.go
> +func GetTasks(search string, searchData bool) (tasks []models.Task, err error) {
рекомендация 

мб вместо  списка параметров передавать структуру - так более гибко будет

2024-10-05 12:10 UTC, dirtymew commented on internal/database/database.go
> +	query := "SELECT * FROM scheduler ORDER BY date LIMIT :limit"
лучше явно поля указывать а не *

2024-10-05 12:10 UTC, dirtymew commented on internal/services/middleware.go
> +		pass := os.Getenv("TODO_PASSWORD")
тут не очень - не стоит делать вызовы к os внутри хендлеров

всю конфигурацию стоит на старте считать и использовать

os.Getenv пораждает syscall это очень затратная операция

2024-10-05 12:10 UTC, dirtymew commented on internal/transport/rest/handlers.go
> +func CreateTaskHandler(w http.ResponseWriter, r *http.Request) {
Рекомендации по рефакторингу

- проверки лучше вынести в методы/функции и другие пакеты
- по архитектуре - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 и в задании про посылки можно подсмотреть как организованы service и storage

2024-10-05 12:10 UTC, dirtymew commented on internal/transport/rest/token.go
> +	pass := os.Getenv("TODO_PASSWORD")
уже писал выше про это - в хендлерах так делать не нужно

2024-10-05 17:31 UTC, UnknownHik commented on internal/transport/rest/handlers.go
> +func CreateTaskHandler(w http.ResponseWriter, r *http.Request) {
Не совсем понял рекомендации. Могли бы более подробно расписать, пожалуйста?
Проверки я хотел вынести в отельную функцию, так как они повторяются в CreateTaskHandler и UpdateTaskHandler. Но в UpdateTaskHandler немного по-другому сделана проверка даты, поэтому тесты не проходят. Надо бы полностью пересмотреть логику проверки даты, чтобы выделить проверки в отдельную функцию.
По архитектуре ссылался на статью на Хабре (https://habr.com/ru/companies/inDrive/articles/690088/). Я что-то не так понял?

2024-10-06 09:47 UTC, dirtymew approved these changes
Привет Алексей

работу принимаю

поздравляю и желаю удачи

2024-10-06 09:47 UTC, dirtymew commented on internal/transport/rest/handlers.go
> +func CreateTaskHandler(w http.ResponseWriter, r *http.Request) {
@UnknownHik 

дизайин и архитектура ПО в не рамок курса - это тема гораздо обширнее чем весь наш курс в несколько раз - в ревью точно не смогу все разьяснить

ты верно уловил направление но немного не понял сути деления на абстракции

у каждой абстракции есть свое предназначение - суть того что она делает и желательно чтобы она делала что-то одно

возьмем транспорт - его задача получить запрос - проверить что в нем, сделать его валидацию и декодинг в сущности приложения - и все по идее на этом его зона отеветвенности заканцивается(ну и все тоже самое в обратном направлении)

далее мы можем сделать абстракцию - например service и уже в нем проверять сами обьекты task(не путать с запросом). На этом слое вся логика по идее должна быть - если мы в ней как-то взаимодействуем с бд то делаем это через элементарые операции по типу CRUD 

в итоге у нас есть 3 уровня абстракции которые никак не связаны между собой - только через свои API (interface)

твое решение не такое 
у тебя транспортый и сервисные уровени обьеденны в один

2024-10-06 10:30 UTC, UnknownHik commented on internal/transport/rest/handlers.go
> +func CreateTaskHandler(w http.ResponseWriter, r *http.Request) {
Спасибо за разъяснение
Все таки переделаю проект в ближайшем будущем с использованием методов и интерфейсов и с учетом ваших рекомендаций
Хочется, чтобы проект был максимально приближен к идеальному)

2024-10-06 20:43 UTC, dirtymew commented on internal/transport/rest/handlers.go
> +func CreateTaskHandler(w http.ResponseWriter, r *http.Request) {
сторадж у тебя верно описан - можно конечно еще на один метод сократить - и сделать  например так
```
FindTask(filter *filter)

type filter struct {
  ID  []string
  Search string
  Date  string
}
```

2024-10-19 16:21 UTC, merged